#Variables
@baseUrl = http://localhost:3333

# Health check
# @name HealthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name GetRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name CreateRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Descrição da sala de teste"
}

###

@roomId = {{CreateRoom.response.body.roomId}}

###

# Get room questions
# @name GetRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions
Accept: application/json
Content-Type: application/json


###

# Create question
# @name CreateQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Accept: application/json
Content-Type: application/json

{
    "question": "Qual é a melhor linguagem de programação?"
}
